#!/usr/bin/env zsh
HOSTNAME=$(hostname)


if (( ${+ENV} )); then
    docker-compose -f "docker-compose.yml" -f "docker-compose.${ENV}.yml" $@
elif [ "${HOSTNAME%%.local}" != "${HOSTNAME}" ]; then
    docker-compose -f "docker-compose.yml" -f "docker-compose.dev.yml" $@
elif (( ${+CI} )); then
    docker-compose -f "docker-compose.yml" -f "docker-compose.ci.yml" $@
else
    docker-compose -f "docker-compose.yml" $@
fi
